
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getAllEvents() : Promise<Result<Partial<{ [key in string]: GoogleEvent[] }>, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_events") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getColors() : Promise<Result<GoogleColorList, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_colors") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTasklists() : Promise<Result<GoogleTasklist[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tasklists") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTasks(tasklist: GoogleTasklist) : Promise<Result<GoogleTask[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tasks", { tasklist }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTask(task: GoogleTask) : Promise<Result<GoogleTask, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_task", { task }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHabits() : Promise<Result<Partial<{ [key in string]: Habit }>, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_habits") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async completeHabit(habit: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("complete_habit", { habit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWeather(location: string) : Promise<Result<LocationWeather, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_weather", { location }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHabitHistory() : Promise<Result<HabitLogs, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_habit_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConfig() : Promise<Result<PublicConfig, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateConfig(pconfig: PublicConfig) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_config", { pconfig }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppError = string
export type Forecast = { time: [number, number, number]; temperature_2m_max: [number, number, number]; temperature_2m_min: [number, number, number] }
export type GoogleColor = { background: string; foreground: string }
export type GoogleColorList = { calendar: Partial<{ [key in string]: GoogleColor }>; event: Partial<{ [key in string]: GoogleColor }> }
export type GoogleDate = { date: string | null; dateTime: string | null }
export type GoogleEvent = { summary: string; description: string | null; id: string; start: GoogleDate; end: GoogleDate; htmlLink: string; colorId: string | null }
export type GoogleTask = { id: string; title: string; status: GoogleTaskStatus; selfLink: string }
export type GoogleTaskStatus = "needsAction" | "completed"
export type GoogleTasklist = { title: string; id: string }
export type Habit = { name: string; frequency: HabitFrequency; max: number; amount: number; timestamp: number }
export type HabitFrequency = "daily" | "weekly"
export type HabitLogs = { daily: Partial<{ [key in number]: Partial<{ [key in string]: Log }> }>; weekly: Partial<{ [key in number]: Partial<{ [key in string]: Log }> }> }
export type LocationWeather = { location: string; current: Weather; daily: Forecast }
export type Log = { count: number; max: number }
export type PublicConfig = { location: string; refresh_token: string }
export type Weather = { time: number; interval: number; relative_humidity_2m: number; temperature_2m: number; apparent_temperature: number; is_day: number; precipitation: number; rain: number; weather_code: number; wind_speed_10m: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
